### ISSUE TITLE
tkinter look bad in linux(kde)

### ISSUE THREAD

**Issue by YoyPa** [fourminute/Fluffy#29]
Fluffy 2.5 on the left, fluffy 2.4 on the right
![fluffy-dialog](https://user-images.githubusercontent.com/29115747/51957971-b89ab200-2445-11e9-9b7b-b71badbd3da2.png)

**Comment by fourminute** [comment]
I'm aware, this was intentional. The old file dialog was not compatible with MacOS systems, I kept getting bug reports that I couldn't keep up with using the PyQt5 file dialog. Unfortunately there was no other way around it. I could have used Kivy or WXPython for the File Dialog process but those introduced new modules.

Tkinter is the only universal file dialog that has the best compatibility and most end-users already have Tkinter.
